# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170225_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
